//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class About
    {
        [Display(Name ="Hakkýmýzda Id")]
        public byte AboutId { get; set; }
        [Display(Name ="Hakkýmýzda Baþlýk")]
        [StringLength(150,ErrorMessage ="En Fazla 150 Karakter Girebilirsiniz")]
        [ Required(ErrorMessage ="Zorunlu Alan")]
        public string AboutTitle { get; set; }
        [Display(Name = "Hakkýmýzda Açýklama")]
  
        public string Description { get; set; }
    }
}
