//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        [Display(Name = "Ýletiþim Id")]
     
        public byte ContactId { get; set; }
        [Display(Name = "Ýletiþim Harita Kodu")]
        [StringLength(350, ErrorMessage = "Uzantý En Az 6 En Fazla 350 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string EmbedCode { get; set; }
        [Display(Name = "Ýletiþim Adres")]
        [StringLength(350, ErrorMessage = " En Az 6 En Fazla 350 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Adress { get; set; }
        [Display(Name = "Ýletiþim E-mail")]
        [StringLength(100, ErrorMessage = "En Az 6 En Fazla 100 Karakter Girebilirsiniz", MinimumLength = 1)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Email { get; set; }
        [Display(Name = "Ýletiþim Telefon")]
        [StringLength(15, ErrorMessage = "En Az 1 En Fazla 15 Karakter Girebilirsiniz", MinimumLength = 1)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Tel { get; set; }
    }
}
