//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public byte FooterId { get; set; }
        public Nullable<bool> SocialMediaActive { get; set; }
        public string FacebookUrl { get; set; }
        public string TwiterUrl { get; set; }
        public string SkypeUrl { get; set; }
    }
}
