//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Home
    {     [Display(Name ="Ana Sayfa Id")]
        public byte HomeId { get; set; }


        [Display(Name = "Logo")]
        [StringLength(250, ErrorMessage = "En Fazla 250 Karakter Girebilirsiniz")]
        public string LogoImgUrl { get; set; }


        [Display(Name = "Ana Sayfa 1. Baþlýk")]

        public string DescriptionOneTitle { get; set; }

        [Display(Name = "Ana Sayfa 1. Baþlýk")]
       
        public string DescriptionOne { get; set; }

        [Display(Name = "Ana Sayfa 2. Baþlýk")]
      
        public string DescriptionTwoTitle { get; set; }

        [Display(Name = "Ana Sayfa 2. Baþlýk")]
    
        public string DescriptionTwo { get; set; }
    }
}
