//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {

        [Display(Name = "Ürün Id")]
        public int ProductId { get; set; }

        [Display(Name = "Kategori Id")]
        public Nullable<byte> CategoryId { get; set; }

        [Display(Name = "Ürün Ýsim")]
        [StringLength(80, ErrorMessage = "En Az 6 En Fazla 80 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Name { get; set; }


        [Display(Name = "Ürün Fiyat")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public Nullable<double> Price { get; set; }

        [Display(Name = "Ürün Açýklama")]
     
        public string Description { get; set; }
        [Display(Name = "Ürün Resim")]
        public string Image { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
