//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Referances
    {
        [Display(Name = "Referans Id")]
        public byte RefId { get; set; }
        [Display(Name = "Referans Baþlýk")]
        [StringLength(150, ErrorMessage = "En Az 6 En Fazla 150 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Title { get; set; }
        [Display(Name = "Referans Resim")]
        [StringLength(250, ErrorMessage = "En Fazla 250 Karakter Girebilirsiniz")]
        public string Image { get; set; }
        [Display(Name = "Referans Ýsim")]
        [StringLength(100, ErrorMessage = " En Az 6 En Fazla 100 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string RefName { get; set; }
    }
}
