//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Slider
    {
        [Display(Name = "Slider Id")]
        public byte SliderId { get; set; }
        [Display(Name = "Slider Resim")]
        [StringLength(250, ErrorMessage = "En Fazla 250 Karakter Girebilirsiniz")]
        public string ImageUrl { get; set; }
        [Display(Name = "Slider Tarih")]
        public Nullable<System.DateTime> RegisterDate { get; set; }
    }
}
