//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavMvcOnurYalcinBagonu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Display(Name = "Kullanýcý Id")]
        public byte UserId { get; set; }
        [Display(Name = "Kullanýcý E-mail")]
        [StringLength(45, ErrorMessage = " En Az 6 En Fazla 45 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string User_Email { get; set; }
        [Display(Name = "Kullanýcý Password")]
        [StringLength(16, ErrorMessage = "En Az 6 En Fazla 16 Karakter Girebilirsiniz", MinimumLength = 6)]
        [Required(ErrorMessage = "Zorunlu Alan")]
      
        public string Password { get; set; }
        [Display(Name = "Kullanýcý Tarih")]
        public Nullable<System.DateTime> Register_Date { get; set; }
    }
}
